general:
  debug: true
servlet:
    port: 8080
unprotectedworlds:
    - plotworld
TeamSpeak:
    enabled: true
    projectChannel: 0
    host: localhost
    QueryUser:
        Name: serveradmin
        Password: Y1SA7DZ+
