name: ${project.artifactId}
main: com.mcmiddleeqrth.thegaffer.TheGaffer
version: ${project.version}
website: ${project.url}
authors: [meggawatts, DonoA]
description: Job API for MCME.
author: meggawatts
commands:
  createjob:
    description: Launches a job creation conversation
    usage: |
           /createjob
  job:
    usage: |
            /job stop <jobname>
            /job check
            /job archive
            /job join <jobname>
            /job warpto <jobname>
            /job info <jobname>
            /job admit <player>
  jobadmin:
    description: Launches the jobadmin conversation
    usage: |
           /jobadmin