name: ${project.artifactId}
main: co.mcme.jobs.Jobs
version: ${project.version}
website: ${project.url}
authors: [meggawatts]
description: Job API for MCME.
author: meggawatts
permissions:
  jobs.run:
    description: Ability to start and stop own jobs.
    default: op
  jobs.ignorestatus:
    description: Ignore job build permissions
    default: op
  jobs.write:
    description: Forces a job to write it's file
    default: op
  jobs.reload:
    description: Reloads job list from file
    default: op
  jobs.ignoreownjob:
    descripton: allows user to bypass the owner restriction on jobs.
    default: op
  jobs.join:
    description: allows joining a running job.
  jobs.check:
    description: allows checking the running jobs.
  jobs.user:
    default: true
    children:
      jobs.join: true
      jobs.check: true
  jobs.admin:
    default: op
    children:
      jobs.ignorestatus: true
      jobs.user: true
      jobs.run: true
      jobs.write: true
      jobs.reload: true
commands:
  job:
    usage: |
            /job <start|stop> <jobname>
            /job check
            /job archive
            /job join <jobname>
            /job warpto <jobname>
            /job info <jobname>
  jobadmin:
    usage: |
           /jobadmin <jobName> <action> <variable>