name: MCMEJobs
main: com.meggawatts.jobs.Jobs
version: 1.0
description: Job API for MCME.
author: meggawatts
permissions:
  jobs.run:
    description: Ability to start and stop own jobs.
    default: op
commands:
  job:
    usage: |
            /job <jobName> <Status>
            /job check